Add ChEBI allow-list.

diff --git a/src/ontology/Makefile b/src/ontology/Makefile
--- a/src/ontology/Makefile
+++ b/src/ontology/Makefile
@@ -714,12 +714,15 @@ reports/neo-violations.report: $(GO_LEGO).owl
 	$(ROBOT) report --input $(GO_LEGO).owl --tdb true --tdb-directory tdb/ -k true -p ../sparql/neo/profile.txt -o $@ --print 50 -v
 
 # intermediate files in this target must be lexically, not numerically sorted, for use with comm
-chebi_pH_7_3_check: reports/referenced_chebi_terms.tsv ../biochebi/chebi_pH7_3_mapping.tsv
+# terms listed in ../biochebi/chebi-allow.txt are exempted from the pH 7.3 requirement
+chebi_pH_7_3_check: reports/referenced_chebi_terms.tsv ../biochebi/chebi_pH7_3_mapping.tsv ../biochebi/chebi-allow.txt
 	tail -n +2 reports/referenced_chebi_terms.tsv | sed 's/<http:\/\/purl.obolibrary.org\/obo\/CHEBI_//g' | sed 's/>//g' | sort -u >tmp_referenced_chebi_nums.txt &&\
 	tail -n +2 ../biochebi/chebi_pH7_3_mapping.tsv | cut -f 1 | sort -u >tmp_mapped_chebi_nums.txt &&\
 	tail -n +2 ../biochebi/chebi_pH7_3_mapping.tsv | cut -f 2 | sort -u >tmp_7_3_chebi_nums.txt &&\
+	grep '^CHEBI:' ../biochebi/chebi-allow.txt | sed 's/^CHEBI://' | sort -u >tmp_chebi_allow_nums.txt &&\
 	comm -23 tmp_referenced_chebi_nums.txt tmp_7_3_chebi_nums.txt >tmp_referenced_chebi_nums_not_7_3.txt &&\
-	if [ -s 'tmp_referenced_chebi_nums_not_7_3.txt' ]; then echo "ERROR: CHEBI IDs should be mapped to pH 7.3:" && cat tmp_referenced_chebi_nums_not_7_3.txt && exit 1; else exit 0; fi
+	comm -23 tmp_referenced_chebi_nums_not_7_3.txt tmp_chebi_allow_nums.txt >tmp_referenced_chebi_nums_not_7_3_not_allowed.txt &&\
+	if [ -s 'tmp_referenced_chebi_nums_not_7_3_not_allowed.txt' ]; then echo "ERROR: CHEBI IDs should be mapped to pH 7.3 (or added to ../biochebi/chebi-allow.txt):" && cat tmp_referenced_chebi_nums_not_7_3_not_allowed.txt && exit 1; else exit 0; fi
 
 # ----------------------------------------
 # REPORTS
